# Generated by Django 4.2.7 on 2024-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_woman', '0002_alter_women_options_women_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
